gantt
    title 日本語IMの歴史
    dateFormat YYYY
    axisFormat %Y
    todayMarker off
    section 東芝
        JW-10(1978,森,真家,et al.):milestone,1978,
    section JustSystem
        KTIS(1983):milestone,1983,
        KTIS2(1984):milestone,1984,
        ATOK(1985-):crit,1985,2026
    section SKK
        SKK(1987-2000,佐藤):done,1987,2000
        Daredevil SKK(1998-):active,1998,2026
    section NEC
        Canna(1989):done,1989,2025
    section Wnn
        Wnn(1987-2005):done,1987,2005
        FreeWnn(1999):1999,2025
        OpenWnn(2008):2008,2025
    section Fujitsu
        OAK:done,1987,1999
        Japanist(-2026):done,2000,2026
    section VACS
        VJE:done,1984,2005
    section K3
        松茸(1986-2013):done,1986,2013
    section A.I.SOFT
        WXシリーズ(1988-2006?):done,1988,2006
    section Microsoft
        Microsoft IME(1993,初代):done,1993,1995
        Microsoft IME 97(1996,自社開発):done,1996,2010
        Microsoft Office Input Method Editor 2010:done,2010,2012
        Microsoft IME(2015-):crit,2015,2026
    section Apple
        ことえり(1992-2012):done,1992,2012
        日本語入力プログラム(2014-):crit,2014,2026
    section Google
        Google日本語入力(2009-):active,2009,2026
        Mozc(2010-):crit,2010,2026
        Gboard(2016-):2016,2026
    section エルゴソフト
        EGBRIDGE:done,1985,2008
    section 物書堂
        かわせみ(2009-):active,2009,2026
    section Miwa
        Azookey(2024-):active,2024,2026

